version: '3'

tasks:
  # https://www.chezmoi.io/docs/how-to/#include-dotfiles-from-elsewhere
  oh-my-zzh:
    cmds:
      - curl -s -L -o oh-my-zsh-master.tar.gz https://github.com/robbyrussell/oh-my-zsh/archive/master.tar.gz
      - chezmoi import --strip-components 1 --destination ${HOME}/.oh-my-zsh oh-my-zsh-master.tar.gz
    silent: true


    


